### ISSUE TITLE
On small screens the time display is not positioned correctly

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#112]
Previously, the optional timestamp window (enabled via a check-box in the reports window) was moved on small screens to account for changing size of navbar (i.e. y-axis position) and changing margin of legend (i.e. x-axis position).

This bug can be replicated by enabling the timestamp and resizing the window. 

<img width="335" alt="screen shot 2016-03-05 at 11 03 47 am" src="https://cloud.githubusercontent.com/assets/944642/13543743/4f67a382-e2c2-11e5-8f40-389814a5d25c.png">

**Comment by matthewberryman** [comment]
It's helpful to figure out what this bug is if you do a before:
![screenshot 2016-03-05 12 25 21](https://cloud.githubusercontent.com/assets/2288238/13544702/738e5606-e2cd-11e5-8718-a79a54977a79.png)
and after shot:
![screenshot 2016-03-05 12 25 28](https://cloud.githubusercontent.com/assets/2288238/13544703/77e4dc34-e2cd-11e5-8e6c-8ad2ebbad9f4.png)

IIRC the behaviour before was that the time and zoom button move up to be the same distance from the nav bar. @talltom can you please confirm what desired behaviour actually is?

Note that this bug doesn't apply to Safari on OS X (no matter what the size it uses the full size nav bar) and not to any browsers on iPhone (since you can't resize the window) but does affect Safari on iPads that support slideover—you have to have it the 1/3rd size window on the right hand side to see it.

**Comment by matthewberryman** [comment]
This applies to IE11, Firefox and Chrome (with Safari behaviour as noted previously).

**Comment by talltom** [comment]
Desired behviour is previous responsiveness (not sure at which point this bug was introduced):
- as the navbar is shrunk for small screens the timestamp box is re-aligned accordingly.

Here's a screenshot of desired behaviour

<img width="329" alt="screen shot 2016-03-05 at 12 48 00 pm" src="https://cloud.githubusercontent.com/assets/944642/13544869/959c28ce-e2d0-11e5-89f6-54ed82eb6140.png">
