### ISSUE TITLE
Dynamic banner sizing leaves white space on mobile devices

### ISSUE THREAD

**Issue by talltom** [smart-facility/petajakarta-web#65]
<img width="338" alt="screen shot 2015-11-17 at 5 06 54 pm" src="https://cloud.githubusercontent.com/assets/944642/11208492/11ca6a42-8d4e-11e5-8a74-11e59c5b0412.png">

**Comment by matthewberryman** [comment]
I don't get this on my 6, will try on our 4s and 5s.

**Comment by matthewberryman** [comment]
Here 'tis on a 5s in the first screenshot (I am pretty sure the same res as a 4s, will test on that once Chloe is awake as she has it in her room). The white bar in the second screenshot only shows up if you scroll up and hold the scroll. It snaps back to rendering without any gap if you let go. Scrolling down the page works perfectly, no white bar. I'd say this is a bug in Chrome developer iPhone preview function.
![image](https://cloud.githubusercontent.com/assets/2288238/11210353/c4345904-8d7b-11e5-8320-3e48c07f57fc.png)
![image](https://cloud.githubusercontent.com/assets/2288238/11210365/d722a26e-8d7b-11e5-819c-26abf9cf072e.png)

**Comment by talltom** [comment]
@matthewberryman it depends on resolution of the device you're using. It occurs on my android phone (firefox and chrome). There was a missing css statement required to push the page up when the nav banner is shrunk on small devices (trying to maximise screeen real estate). The above fix *should* enable consistent rendering across devices. If you can test I would be grateful, but no rush.

**Comment by matthewberryman** [comment]
498586b breaks majorly on iPhone 5s for me, starting partway down the page:
![img_8784](https://cloud.githubusercontent.com/assets/2288238/11257534/39d77c1a-8ea6-11e5-99ef-8d3fa440ab11.PNG)
and then if you scroll up it's still quite broken:
![img_8785](https://cloud.githubusercontent.com/assets/2288238/11257536/421672c8-8ea6-11e5-9e65-d40fd62d76c9.PNG)
It's also looking pretty broken on iPhone 6:
![img_8786](https://cloud.githubusercontent.com/assets/2288238/11257588/a73502a0-8ea6-11e5-9b35-5f27cb6e6da6.PNG)
Where as [before](https://github.com/smart-facility/petajakarta-web/issues/65#issuecomment-157344946) with 38c6c67 it was looking perfect on both, despite Chrome's preview showing white space. You're better off using the Simulator app (Xcode -> Xcode menu -> Open Developer Tool -> Simulator) to run the actual web browser you're wanting to test rather than just its resolution. Note that you can access developer tools for Simulator iOS (and iOS devices) through the Developer menu in Safari on the Mac.

On iPad and Safari Desktop there's a very minor breakage in 498586b. iPad:
![file 19-11-2015 10 10 32](https://cloud.githubusercontent.com/assets/2288238/11257693/6583c020-8ea7-11e5-8b26-c4193799adfe.png)
Safari:
![screenshot 2015-11-19 10 11 30](https://cloud.githubusercontent.com/assets/2288238/11257698/70f78568-8ea7-11e5-9e63-c87bf3a1a78b.png)
I don't recall this being an issue with 38c6c67 and prior but will test locally and report back.

**Comment by matthewberryman** [comment]
Note, I've only just updated my previous comment to refer to the correct commit id where things are working good on iPhone, which is 2f6539c. In that build I still see a few pixels of very slight overlap on iPad and desktop; I guess I just hadn't noticed before.

**Comment by talltom** [comment]
Thanks @matthewberryman, please take a look at 7fb614a3cab161162f6a2c8142269ea1dd2661f4 in which I add the "device-min-width" to the selector which can help with Apple/Safari devices (ref: http://stackoverflow.com/questions/16301910/iphone-is-ignoring-css-media-queries-viewport-tag-present-working-in-desktop)

**Comment by matthewberryman** [comment]
This is working perfectly on desktop and iPad Air 2 hardware (without the slight overlap), and iPhone 6 (hardware) and (simulated) 4s and 5s and it looks fine. I will double check on 5s and 4s hardware at home tonight but I'm happy to close now.

**Comment by matthewberryman** [comment]
The issue has come back with recent changes; on my iPhone 6 the position is out again.
![image](https://cloud.githubusercontent.com/assets/2288238/11464090/db3c18dc-977e-11e5-9c7b-d34ed698165e.png)

**Comment by matthewberryman** [comment]
The issue has come back again with recent changes; on my iPhone 6 the starting position is out.
![image](https://cloud.githubusercontent.com/assets/2288238/11464102/291f1fd6-977f-11e5-8ad6-7837bf741008.jpeg)

**Comment by matthewberryman** [comment]
I haven't been able to reproduce the starting position bug on either dev or rem this morning.

**Comment by talltom** [comment]
I am not able to reproduce this on either physical devices (iPhone 5/s), Chrome developer mode, XCode emulator - perhaps dev was a little behind my commits on this, or it was a caching issue?

**Comment by matthewberryman** [comment]
Yeah, I haven't been able to reproduce, so I'm closing again. Suspect a caching issue (apologies, I should have cleared my mobile cache).

**Comment by matthewberryman** [comment]
To reproduce you need to clear the cache (or use private mode on Safari to achieve the same thing).

**Comment by matthewberryman** [comment]
I guess you know, but just reporting that c34939b hasn't fixed it.

**Comment by matthewberryman** [comment]
Fixed by https://github.com/smart-facility/petajakarta-web/pull/74
